[workspace]
members = [
    "rustdebugging",
    "shownathan",
    "programming_rust_2e/mandelbrot",
    "programming_rust_2e/quickreplace",
]

resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
