[workspace]
members = [
    "rustdebugging",
    "programming_rust_2e/mandelbrot",
    "programming_rust_2e/quickreplace",
    "wasm-game-of-life",
]
resolver = "2"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
