[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"
description = "The Mandelbrot example from Programming Rust 2nd Edition Chapter 2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.13.0"
num = "0.4.1"
